# Generated by Django 4.0.3 on 2022-04-22 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0013_alter_car_car_brand_alter_car_car_model_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
